version: "3.8"
services:
  postgres:
    container_name: ${DB_NAME:-db}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/posgresql/data
    restart: unless-stopped
    networks:
      - postgres

  server:
    container_name: server
    image: node:18
    depends_on:
      - postgres
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
      - "${PRISMA_STUDIO_PORT:-5555}:${PRISMA_STUDIO_PORT:-5555}"
    restart: always
    command: /bin/sh -c "curl -fsSL https://bun.sh/install | bash && npm i && ~/.bun/bin/./bun run --hot app.js"
    environment:
      SERVER_PORT: ${SERVER_PORT:-3000}
      PRISMA_STUDIO_PORT: ${PISMA_STUDIO_PORT:-5555}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_CONNECTION_STRING: ${PG_CONNECTION_STRING}
    volumes:
      - "./server:/app"
    working_dir: /app
    networks:
      - postgres

  # front:
  #   container_name: front
  #   image: node:latest
  #   volumes:
  #     - ./front/:/app
  #   working_dir: /app
  #   command: sh -c "npm install && npm run dev"
  #   ports:
  #     - "${FRONT_PORT:-5000}:${FRONT_PORT:-5000}"

volumes:
  postgres_data:
    driver: local

networks:
  postgres:
    driver: bridge
