import withAuth from "./withAuth";
import "./globals.css";
import { Provider } from "react-redux";
export const metadata = {
  title: "create next app",
  description: "generated by create next app",
};

export default function rootlayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
